dependencies:
  - name: alertmanager
    version: 0.0.13
    repository: file://../alertmanager
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployAlertManager

  - name: prometheus
    version: 0.0.24
    repository: file://../prometheus
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-coredns
    version: 0.0.1
    repository: file://../exporter-coredns
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployCoreDNS

  - name: exporter-kube-controller-manager
    version: 0.1.7
    repository: file://../exporter-kube-controller-manager
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kube-dns
    version: 0.1.5
    repository: file://../exporter-kube-dns
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployKubeDNS

  - name: exporter-kube-etcd
    version: 0.1.9
    repository: file://../exporter-kube-etcd
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kube-scheduler
    version: 0.1.6
    repository: file://../exporter-kube-scheduler
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kube-state
    version: 0.1.15
    repository: file://../exporter-kube-state
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kubelets
    version: 0.2.7
    repository: file://../exporter-kubelets
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kubernetes
    version: 0.1.6
    repository: file://../exporter-kubernetes
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-node
    version: 0.2.0
    repository: file://../exporter-node
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployExporterNode

  - name: grafana
    version: 0.0.24
    repository: file://../grafana
    #prod-repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployGrafana
