apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "exporter-coredns.name" . }}
    component: coredns
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "exporter-coredns.fullname" . }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics-coredns
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    k8s-app: coredns
  type: ClusterIP
